version: '2'
services:
  rabbit_mq:
    image: rabbitmq:3.6.8-management
    ports:
    - "8080:8080"
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"
  web_message:
    build: ./web
    ports: 
    - "8000:5000"
    environment:
    - RABBITMQ_DEFAULT_VHOST=vhost
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    links:
    - rabbit_mq
  weather_timer:
    build: ./timers/weather
    # The arguments are:
    # 1 - Base url to weather service "http://api.openweathermap.org"
    # 2 - Relative Path to the resource.  This has the key in it - "data/2.5/weather?zip=48307,us&appid="
    # 3 - The base url for the web service to send messages to.  This is in the docker compose file.
    # 4 - The relative path for the message service
    # dotnet run "http://api.openweathermap.org" "data/2.5/weather?zip=48307,us&appid=" "web_message:8000" "api/message"
    entrypoint: ["dotnet", "run", "http://api.openweathermap.org/", "data/2.5/weather?zip=48307,us&appid=", "http://web_message:5000/", "api/message"]
    links:
    - web_message
#
#  web:
#    build: .
#    ports:
#    - "5000:5000"
#    volumes:
#    - .:/code
#    - logvolume01:/var/log
#    links:
#    - redis
#  redis:
#    image: redis
#volumes:
#  logvolume01: {}