version: '2'
services:
  rabbit_mq:
    image: ronnyroos/rpi-rabbitmq #for raspberry pi
    ports:
    - "8080:8080"
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"
  web_message:
    build: ./web/golang
    ports: 
    - "8000:5000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    entrypoint: ["./main", "amqp://guest:guest@rabbit_mq", "containers_weather_timer_1", "containers_forecast_timer_1"]
    links:
    - rabbit_mq
  time_timer:
    build: ./timers/time
    entrypoint: ["./main", "http://web_message:5000/api/message"]
    links:
    - web_message
  weather_timer:
    build: ./timers/weather
    entrypoint: ["./main", "http://web_message:5000/api/message", "http://api.openweathermap.org/data/2.5/weather?zip=48307,us&appid="]
    links:
    - web_message
  message_timer:
    build: ./timers/message
    entrypoint: ["./main", "http://web_message:5000/api/message", "WiFi"]
    links:
    - web_message
    # docker run containers_message_timer ./main http://192.168.10.122:8000/api/message derp
  forecast_timer:
    build: ./timers/forecast
    entrypoint: ["./main", "http://web_message:5000/api/message", "http://api.openweathermap.org/data/2.5/forecast?zip=48307,us&appid="]
    links:
    - web_message
  serial:
    build: ./serial/golang
    entrypoint: ["./main", "amqp://guest:guest@rabbit_mq", "/dev/ttyUSB0"]
    links:
    - web_message
    devices:
    - "/dev/ttyACM0:/dev/ttyUSB0"