version: '2'
services:
  rabbit_mq:
    image: ronnyroos/rpi-rabbitmq #for raspberry pi
    ports:
    - "8080:8080"
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"
  web_message:
    build: ./web/golang
    ports: 
    - "8000:5000"
    entrypoint: ["./main", "amqp://guest:guest@rabbit_mq"]
    links:
    - rabbit_mq
  #weather_timer:
  #  build: ./timers/weather
    # The arguments are:
    # 1 - Base url to weather service "http://api.openweathermap.org"
    # 2 - Relative Path to the resource.  This has the key in it - "data/2.5/weather?zip=48307,us&appid="
    # 3 - The base url for the web service to send messages to.  This is in the docker compose file.
    # 4 - The relative path for the message service
    # dotnet run "http://api.openweathermap.org" "data/2.5/weather?zip=48307,us&appid=" "web_message:8000" "api/message"
  #  entrypoint: ["dotnet", "run", "http://api.openweathermap.org/", "data/2.5/weather?zip=48307,us&appid=", "http://web_message:5000/", "api/message"]
  #  links:
  #  - web_message
  serial:
    build: ./serial/golang
    entrypoint: ["./main", "amqp://guest:guest@rabbit_mq", "/dev/ttyUSB0"]
    links:
    - web_message
    devices:
    - "/dev/ttyACM0:/dev/ttyUSB0"