version: '2'
services:
  rabbit_mq:
    image: rabbitmq:3.6.8-management
    ports:
    - "8080:8080"
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"
  web_message:
    build: ./web
    ports: 
    - "8000:5000"
    environment:
    - RABBITMQ_DEFAULT_VHOST=vhost
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    links:
    - rabbit_mq
#
#  web:
#    build: .
#    ports:
#    - "5000:5000"
#    volumes:
#    - .:/code
#    - logvolume01:/var/log
#    links:
#    - redis
#  redis:
#    image: redis
#volumes:
#  logvolume01: {}