version: '2'
services:
  rabbit_mq:
    image: supermitsuba/rpi-rabbitmq:1 #for raspberry pi
    ports:
    - "8080:8080"
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"
    container_name: rabbit_mq
  base-sms:
    image: supermitsuba/basesms:1
    container_name: base-sms
  web_message:
    image: supermitsuba/web_message:1
    ports: 
    - "8000:5000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    entrypoint: ["./main", "amqp://guest:guest@rabbit_mq", "http://api.openweathermap.org/data/2.5/weather?zip=48307,us&appid=", "http://api.openweathermap.org/data/2.5/forecast?zip=48307,us&appid="]
    links:
    - rabbit_mq
    depends_on:
    - base-sms
  time_timer:
    image: supermitsuba/time_timer:1
    entrypoint: ["./main", "http://web_message:5000/api/message"]
    links:
    - web_message
    container_name: time
    depends_on:
    - base-sms
  weather_timer:
    image: supermitsuba/weather_timer:1
    entrypoint: ["./main", "http://web_message:5000/api/message", "http://api.openweathermap.org/data/2.5/weather?zip=48307,us&appid="]
    links:
    - web_message
    depends_on:
    - base-sms
    container_name: weather
  message_timer:
    image: supermitsuba/message_timer:1
    entrypoint: ["./main", "http://web_message:5000/api/message", "WiFi"]
    links:
    - web_message
    depends_on:
    - base-sms
    # docker run containers_message_timer ./main http://192.168.10.122:8000/api/message derp
  forecast_timer:
    image: supermitsuba/forecast_timer:1
    entrypoint: ["./main", "http://web_message:5000/api/message", "http://api.openweathermap.org/data/2.5/forecast?zip=48307,us&appid="]
    links:
    - web_message
    - base-sms
    container_name: forecast
  serial:
    image: supermitsuba/client_sms:1
    entrypoint: ["./main", "amqp://guest:guest@rabbit_mq", "/dev/ttyUSB0"]
    links:
    - web_message
    depends_on:
    - base-sms
    devices:
    - "/dev/ttyACM0:/dev/ttyUSB0"
